[project]
name = "perception"
version = "0.0.4"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.12.0"
dependencies = [
    "fastapi>=0.128.1",
    "python-multipart>=0.0.22",
    "svgutils>=0.3.4",
    "uvicorn>=0.40.0",
]
